apiVersion: v1
kind: Service
metadata:
  name: users-citus-worker1-service
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: users-citus-worker1-deployment
  type: LoadBalancer
