apiVersion: v1
kind: Service
metadata:
  name: users-citus-worker2-service
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: users-citus-worker2-deployment
  type: LoadBalancer
