apiVersion: v1
kind: Service
metadata:
  name: users-citus-coordinator-service
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: users-citus-coordinator-deployment
  type: LoadBalancer
