apiVersion: v1
kind: PersistentVolume
metadata:
  name: users-citus-coordinator-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/pv/users-citus-coordinator-pv"
    type: DirectoryOrCreate 

  claimRef:                
    namespace: default     
    name: users-citus-coordinator-pvc 
