apiVersion: v1
kind: PersistentVolume
metadata:
  name: users-citus-worker1-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: manual
  hostPath:
    path: "/mnt/pv/users-citus-worker1-pv"
    type: DirectoryOrCreate 

  claimRef:                
    namespace: default     
    name: users-citus-worker1-pvc 
