apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: users-citus-worker1-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: manual
